//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingStartedLib
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="people", Namespace="http://schemas.datacontract.org/2004/07/GettingStartedLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GettingStartedLib.Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class people : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string[] RoomsField;
        
        private object callbackField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Rooms
        {
            get
            {
                return this.RoomsField;
            }
            set
            {
                this.RoomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object callback
        {
            get
            {
                return this.callbackField;
            }
            set
            {
                this.callbackField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GettingStartedLib")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CurrentUserField;
        
        private string UserMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentUser
        {
            get
            {
                return this.CurrentUserField;
            }
            set
            {
                this.CurrentUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserMessage
        {
            get
            {
                return this.UserMessageField;
            }
            set
            {
                this.UserMessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IChat", CallbackContract=typeof(IChatCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IChat
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/Subscribe", ReplyAction="http://tempuri.org/IChat/SubscribeResponse")]
    bool Subscribe(string Name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/Subscribe", ReplyAction="http://tempuri.org/IChat/SubscribeResponse")]
    System.Threading.Tasks.Task<bool> SubscribeAsync(string Name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/UnSubscribe", ReplyAction="http://tempuri.org/IChat/UnSubscribeResponse")]
    bool UnSubscribe();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/UnSubscribe", ReplyAction="http://tempuri.org/IChat/UnSubscribeResponse")]
    System.Threading.Tasks.Task<bool> UnSubscribeAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/create_private_room", ReplyAction="http://tempuri.org/IChat/create_private_roomResponse")]
    void create_private_room(GettingStartedLib.people man, string name_of_room);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/create_private_room", ReplyAction="http://tempuri.org/IChat/create_private_roomResponse")]
    System.Threading.Tasks.Task create_private_roomAsync(GettingStartedLib.people man, string name_of_room);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/add_usver_to_private_room", ReplyAction="http://tempuri.org/IChat/add_usver_to_private_roomResponse")]
    void add_usver_to_private_room(string usver_name, string room);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/add_usver_to_private_room", ReplyAction="http://tempuri.org/IChat/add_usver_to_private_roomResponse")]
    System.Threading.Tasks.Task add_usver_to_private_roomAsync(string usver_name, string room);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/send_private_message", ReplyAction="http://tempuri.org/IChat/send_private_messageResponse")]
    void send_private_message(GettingStartedLib.Message new_message, string private_room);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/send_private_message", ReplyAction="http://tempuri.org/IChat/send_private_messageResponse")]
    System.Threading.Tasks.Task send_private_messageAsync(GettingStartedLib.Message new_message, string private_room);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/craete_new_man", ReplyAction="http://tempuri.org/IChat/craete_new_manResponse")]
    void craete_new_man(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/craete_new_man", ReplyAction="http://tempuri.org/IChat/craete_new_manResponse")]
    System.Threading.Tasks.Task craete_new_manAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SendMessage", ReplyAction="http://tempuri.org/IChat/SendMessageResponse")]
    void SendMessage(GettingStartedLib.Message message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChat/SendMessage", ReplyAction="http://tempuri.org/IChat/SendMessageResponse")]
    System.Threading.Tasks.Task SendMessageAsync(GettingStartedLib.Message message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/on_new_message")]
    void on_new_message(string new_message);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/on_new_usver")]
    void on_new_usver(string Usver_name);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/on_create_new_room")]
    void on_create_new_room(string new_room);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatChannel : IChat, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ChatClient : System.ServiceModel.DuplexClientBase<IChat>, IChat
{
    
    public ChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public bool Subscribe(string Name)
    {
        return base.Channel.Subscribe(Name);
    }
    
    public System.Threading.Tasks.Task<bool> SubscribeAsync(string Name)
    {
        return base.Channel.SubscribeAsync(Name);
    }
    
    public bool UnSubscribe()
    {
        return base.Channel.UnSubscribe();
    }
    
    public System.Threading.Tasks.Task<bool> UnSubscribeAsync()
    {
        return base.Channel.UnSubscribeAsync();
    }
    
    public void create_private_room(GettingStartedLib.people man, string name_of_room)
    {
        base.Channel.create_private_room(man, name_of_room);
    }
    
    public System.Threading.Tasks.Task create_private_roomAsync(GettingStartedLib.people man, string name_of_room)
    {
        return base.Channel.create_private_roomAsync(man, name_of_room);
    }
    
    public void add_usver_to_private_room(string usver_name, string room)
    {
        base.Channel.add_usver_to_private_room(usver_name, room);
    }
    
    public System.Threading.Tasks.Task add_usver_to_private_roomAsync(string usver_name, string room)
    {
        return base.Channel.add_usver_to_private_roomAsync(usver_name, room);
    }
    
    public void send_private_message(GettingStartedLib.Message new_message, string private_room)
    {
        base.Channel.send_private_message(new_message, private_room);
    }
    
    public System.Threading.Tasks.Task send_private_messageAsync(GettingStartedLib.Message new_message, string private_room)
    {
        return base.Channel.send_private_messageAsync(new_message, private_room);
    }
    
    public void craete_new_man(string name)
    {
        base.Channel.craete_new_man(name);
    }
    
    public System.Threading.Tasks.Task craete_new_manAsync(string name)
    {
        return base.Channel.craete_new_manAsync(name);
    }
    
    public void SendMessage(GettingStartedLib.Message message)
    {
        base.Channel.SendMessage(message);
    }
    
    public System.Threading.Tasks.Task SendMessageAsync(GettingStartedLib.Message message)
    {
        return base.Channel.SendMessageAsync(message);
    }
}
